# Generated by Django 5.0.7 on 2024-11-04 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('logo', models.CharField(default='public/assets/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_inicio', models.PositiveIntegerField()),
                ('anio_fin', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_esperado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='Concentrado.entidad')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='Concentrado.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.IntegerField()),
                ('numero_designados', models.IntegerField()),
                ('numero_inscritos', models.IntegerField()),
                ('inscritos_designados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('con_ingreso', models.IntegerField()),
                ('con_ingreso_inscritos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sin_ingreso', models.IntegerField()),
                ('sin_ingreso_inscritos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('concluyeron', models.IntegerField()),
                ('concluyeron_designados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='Concentrado.entidad')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='Concentrado.periodo')),
            ],
        ),
    ]
