# Generated by Django 5.0.7 on 2024-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.IntegerField()),
                ('nombreEntidad', models.CharField(max_length=255)),
                ('distrito', models.IntegerField()),
                ('numeroDesignados', models.IntegerField()),
                ('numeroInscritos', models.IntegerField()),
                ('inscritosDesignados', models.IntegerField()),
                ('ingreso', models.IntegerField()),
                ('ingresoInscritos', models.IntegerField()),
                ('sinIngreso', models.IntegerField()),
                ('concluyeron', models.IntegerField()),
                ('concluyeronDesignados', models.IntegerField()),
                ('nivelEsperado', models.IntegerField()),
                ('nivelObtenido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
